# Verificacion de la calidad de la tabla plata.productos_crediticios

Proposito del script:  
- Verificar columna por columna la calidad de los datos.

# Estableciendo Conexion

In [1]:
# Importando librerias y estableciendo conexion 
import pandas as pd 
from conexiones_y_rutas import obtener_engine
engine = obtener_engine()

df_productos_crediticios = pd.read_sql(
    "SELECT * FROM plata.productos_crediticios",
    con=engine
)
df_productos_tra = df_productos_crediticios.copy()

# Resumen Columnas

- **producto_id**: Identificador unico de cada producto. 
- **nombre_producto**: Nombre del producto.     
- **tipo_credito**: Tipo de Credito (ejem: 'Personal', 'Vehicular').
- **tasa_nom_min**: Tasa nominal minima para dicho producto.
- **tasa_nom_max**: Tasa nominal maxima para dicho producto.
- **plazo_min_meses**: Plazo mínimo de meses para dicho credito.
- **plazo_max_meses**: Plazo maximo de meses para dicho credito.
- **monto_minimo**: Monto minimo que se tiene que aprobar para dicho credito.
- **monto_maximo**: Monto maximo que se tiene que aprobar para dicho credito.
- **requiere_garantia**: Valor booleano que verifica si el credito requiere o no garantia.
- **moneda**: Moneda en la que se realiza el credito (ejem: 'PEN' y'USD').

# Verificacion de la Calidad de Datos

In [2]:
df_productos_tra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   producto_id        8 non-null      int64
 1   nombre_producto    8 non-null      object
 2   tipo_credito       8 non-null      object
 3   tasa_nom_min       8 non-null      float64
 4   tasa_nom_max       8 non-null      float64
 5   plazo_min_meses    8 non-null      int64
 6   plazo_max_meses    8 non-null      int64
 7   monto_minimo       8 non-null      float64
 8   monto_maximo       7 non-null      float64
 9   requiere_garantia  8 non-null      object
 10  moneda             8 non-null      object
 11  dwh_fecha_carga    8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(3), object(4)
memory usage: 896.0+ bytes

In [3]:
df_productos_tra.head()

,producto_id,nombre_producto,tipo_credito,tasa_nom_min,tasa_nom_max,plazo_min_meses,plazo_max_meses,monto_minimo,monto_maximo,requiere_garantia,moneda,dwh_fecha_carga
0,1,Crédito Personal Libre Disponibilidad,Personal,18.0,36.0,6,60,1000.0,50000.0,0,PEN,2026-08-03 18:46:03.850
1,2,Crédito Hipotecario Vivienda,Hipotecario,7.5,11.0,60,360,50000.0,1000000.0,1,PEN,2026-08-03 18:46:03.850
2,3,Crédito Vehicular,Vehicular,2.5,18.0,12,72,10000.0,200000.0,1,PEN,2026-08-03 18:46:03.850
3,4,Crédito MYPE Capital De Trabajo,Microempresa,20.0,48.0,6,48,2000.0,100000.0,0,PEN,2026-08-03 18:46:03.850
4,5,Crédito de Consumo,Consumo,24.0,42.0,3,36,500.0,20000.0,0,PEN,2026-08-03 18:46:03.850

In [4]:
# Verifica si existen duplicados
# Resultados Esperados: Tabla Vacia  
df_productos_tra[df_productos_tra.duplicated(keep=False)]

Empty DataFrame
Columns: [producto_id, nombre_producto, tipo_credito, tasa_nom_min, tasa_nom_max, plazo_min_meses, plazo_max_meses, monto_minimo, monto_maximo, requiere_garantia, moneda, dwh_fecha_carga]
Index: []

## producto_id

In [5]:
# Verifica si existen ids negativos o 0 
# Resultados Esperados: Tabla Vacia
df_productos_tra[df_productos_tra.producto_id <= 0]

Empty DataFrame
Columns: [producto_id, nombre_producto, tipo_credito, tasa_nom_min, tasa_nom_max, plazo_min_meses, plazo_max_meses, monto_minimo, monto_maximo, requiere_garantia, moneda, dwh_fecha_carga]
Index: []

In [6]:
# Verifica si existen ids duplicados
# Resultados Esperados: Tabla Vacia
df_productos_tra.producto_id[df_productos_tra.producto_id.duplicated(keep=False)]

Series([], Name: producto_id, dtype: int64)

## nombre_producto

In [7]:
# Verifica si los nombres no tienen el formato adecuado
# Resultados Esperados: Crédito MYPE Capital de Trabajo,Crédito de Consumo, Crédito Hipotecario USD
df_productos_tra.nombre_producto[df_productos_tra.nombre_producto 
                                != df_productos_tra.nombre_producto.str.strip().str.title()].unique()

array(['Crédito MYPE Capital De Trabajo', 'Crédito de Consumo',
       'Crédito Hipotecario USD'], dtype=object)

In [8]:
df_productos_tra.nombre_producto.unique()

array(['Crédito Personal Libre Disponibilidad',
       'Crédito Hipotecario Vivienda', 'Crédito Vehicular',
       'Crédito MYPE Capital De Trabajo', 'Crédito de Consumo',
       'Crédito Educativo', 'Crédito Hipotecario USD',
       'Crédito Agropecuario'], dtype=object)

## tipo_credito

In [9]:
# Resultados Esperados: 'Personal', 'Hipotecario', 'Vehicular', 'Microempresa', 'Consumo', 'n/a'
df_productos_tra.tipo_credito.unique()

array(['Personal', 'Hipotecario', 'Vehicular', 'Microempresa', 'Consumo'],
      dtype=object)

## tasa_nom_min

In [10]:
# Verifica si existen tasas nominales menores o iguales a 0
# Resultados Esperados: Tabla Vacia 
df_productos_tra.tasa_nom_min[df_productos_tra.tasa_nom_min <= 0 ]

Series([], Name: tasa_nom_min, dtype: float64)

## tasa_nom_max

In [11]:
# Resultados Esperados: Tabla Vacia 
df_productos_tra.tasa_nom_max[df_productos_tra.tasa_nom_max <= 0 ]

Series([], Name: tasa_nom_max, dtype: float64)

## plazo_min_meses

In [12]:
# Verifica si existen plazo de meses minimos menores o iguales a 0
# Resultados Esperados: Tabla Vacia 
df_productos_tra.plazo_min_meses[df_productos_tra.plazo_min_meses <= 0 ]

Series([], Name: plazo_min_meses, dtype: int64)

## plazo_max_meses

In [13]:
# Verifica si existen plazo de meses maximos menores o iguales a 0
# Resultados Esperados: Tabla Vacia 
df_productos_tra.plazo_max_meses[df_productos_tra.plazo_max_meses <= 0 ]

Series([], Name: plazo_max_meses, dtype: int64)

## monto_minimo

In [14]:
# Verifica si existen montos minimos menores o iguales a 0 
# Resultados Esperados: Tabla Vacia 
df_productos_tra.monto_minimo[df_productos_tra.monto_minimo <= 0]

Series([], Name: monto_minimo, dtype: float64)

## monto_maximo

In [15]:
# Verifica si existen montos maximos menores o iguales a 0 
# Resultados Esperados: Tabla Vacia 
df_productos_tra.monto_maximo[df_productos_tra.monto_maximo <= 0]

Series([], Name: monto_maximo, dtype: float64)

In [16]:
# Verifica si existen registros donde el monto maximo sea menor o igual al monto minimo 
# Resultados Esperados: Tabla Vacia 
df_productos_tra[["monto_minimo","monto_maximo"]][df_productos_tra.monto_maximo 
                                                        <= df_productos_tra.monto_minimo]

Empty DataFrame
Columns: [monto_minimo, monto_maximo]
Index: []

## requiere_garantia

In [17]:
# Cambia de Object a boolean 
df_productos_tra["requiere_garantia"] = (
    df_productos_tra["requiere_garantia"]
    .astype(int)
    .astype(bool)
)

In [18]:
# Verifica si existen registros incorrectos
# Resultados Esperados: True, False, nan
df_productos_tra.requiere_garantia.unique()

array([False,  True])

## moneda

In [19]:
# Resultados Esperados: 'PEN', 'USD', 'n/a'
df_productos_tra.moneda.unique()

array(['PEN', 'USD'], dtype=object)