# Verificacion de la calidad de la tabla plata.clientes

Proposito del script:  
- Verificar columna por columna la calidad de los datos.

## Estableciendo la Conexion

In [1]:
# Importando Librerias y Cargando Archivos
import pandas as pd 
from datetime import date
from conexiones_y_rutas import obtener_engine,obtener_ruta_archivo
engine = obtener_engine()
df_clientes = pd.read_sql(
    "SELECT * FROM plata.clientes",
    con=engine
)
df_clientes_tra = df_clientes.copy()

# Archivos de Ayuda

**Nota**: Este archivo se va utilizar para verificar las siguientes columnas:  
- [Ciudad Residencia](#ciudad_residencia)
- [Departamento Residencia](#departamento_residencia)
- [Region Residencia](#region_residencia)

In [2]:
# df del registro de ciudades de la empresa
df_ciudades = pd.read_csv(obtener_ruta_archivo("archivos_de_ayuda","peru_ciudades.csv"))
df_ciudades_tra = df_ciudades.copy()
df_ciudades_tra.head()

      ciudad departamento region
0     Tumbes       Tumbes  Norte
1  Zarumilla       Tumbes  Norte
2   Zorritos       Tumbes  Norte
3      Piura        Piura  Norte
4    Sullana        Piura  Norte

In [3]:
# se va a usar para validar sucursal_id y fecha_registro 
df_sucursales = pd.read_sql(
    "SELECT sucursal_id, fecha_apertura FROM plata.sucursales",
    con=engine
)
df_sucursales_tra = df_sucursales.copy()
df_sucursales_tra.head()

   sucursal_id fecha_apertura
0            1     2005-07-24
1            2     2010-01-03
2            3     2007-04-20
3            4     2010-02-19
4            5     2007-02-07

In [4]:
df_sucursales_tra["fecha_apertura"] = pd.to_datetime(df_sucursales_tra.fecha_apertura)

# Resumen de las Columnas

- **cliente_id**: Identificador unico de cada cliente.  
- **tipo_documento**: Documento de registro del cliente (ejem: DNI o CE).  
- **numero_documento**: Numero del documento del cliente, la cantidad de digitos depende del tipo de documento.  
- **nombres**: Nombres del clientes.  
- **apellido_paterno**: Apellido paterno del cliente.  
- **apellido_materno**: Apellido materno del cliente.  
- **fecha_nacimiento**: Fecha de nacimiento del cliente.  
- **edad**: Edad actual del cliente.   
- **genero**: Genero del cliente (ejem: Masculino o Femenino).  
- **estado_civil**: Estado civil del cliente (ejem: Soltero, Casado).  
- **nivel_educacion**: Nivel de educacion del cliente (ejem: Secundaria o Universitaria).  
- **ocupacion**: Ocupacion actual del cliente (ejem: Empleado Publico y Empresario).  
- **sector_economico**: Sector economico donde se desarrolla el cliente (ejem: Finanzas o Transporte).  
- **ciudad_residencia**: Ciudad de residencia del cliente (ejmp: Santiago De Surco o La Esperanza).  
- **departamento_residencia**: Departamento de residencia del cliente (ejmp: Ica o Arequipa).  
- **region_residencia**: Region de residencia del cliente (ejmp: Norte o Sur).  
- **ingresos_mensuales**: Ingresos mensuales del cliente.  
- **egresos_mensuales**: Egresos mensuales del cliente.  
- **patrimonio_estimado**: Valuacion del patrimonio estimado del cliente.  
- **score_crediticio**: Score crediticio del cliente (0-1000).  
- **segmento_cliente**: Segmento del cliente (ejem: Regular, Premium o VIP).  
- **canal_captacion**: Canal de captacion del cliente (ejem: Agencia o Digital).  
- **fecha_registro**: Fecha de registro de cliente en el banco.  
- **antiguedad_clientes_meses**: Antiguedad de cliente en meses.  
- **sucursal_id**: Identificador unico de la sucursal donde esta inscrito cada cliente.  
- **estado_cliente**: Estado actual del cliente (ejem: Activo, Inactivo o Bloqueado).

# Verificacion de la Calidad de Datos

In [5]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   cliente_id                5000 non-null   int64
 1   tipo_documento            5000 non-null   object
 2   numero_documento          5000 non-null   object
 3   nombres                   5000 non-null   object
 4   apellido_paterno          5000 non-null   object
 5   apellido_materno          5000 non-null   object
 6   fecha_nacimiento          5000 non-null   object
 7   edad                      5000 non-null   int64
 8   genero                    5000 non-null   object
 9   estado_civil              5000 non-null   object
 10  nivel_educacion           5000 non-null   object
 11  ocupacion                 5000 non-null   object
 12  sector_economico          5000 non-null   object
 13  ciudad_residencia         5000 non-null   object
 14  departamento_residencia   5000 non-null   object
 15  region_residencia         5000 non-null   object
 16  ingresos_mensuales        4892 non-null   float64
 17  egresos_mensuales         5000 non-null   float64
 18  patrimonio_estimado       5000 non-null   float64
 19  score_crediticio          5000 non-null   int64
 20  segmento_cliente          5000 non-null   object
 21  canal_captacion           5000 non-null   object
 22  antiguedad_cliente_meses  5000 non-null   int64
 23  fecha_registro            5000 non-null   object
 24  sucursal_id               5000 non-null   int64
 25  estado_cliente            5000 non-null   object
 26  dwh_fecha_carga           5000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(5), object(18)
memory usage: 1.0+ MB

In [6]:
columnas_fecha = [
    "fecha_nacimiento",
    "fecha_registro"
]

for columna in columnas_fecha:
    df_clientes_tra[columna] = pd.to_datetime(df_clientes_tra[columna])

In [7]:
df_clientes_tra.head()

,cliente_id,tipo_documento,numero_documento,nombres,apellido_paterno,apellido_materno,fecha_nacimiento,edad,genero,estado_civil,...,egresos_mensuales,patrimonio_estimado,score_crediticio,segmento_cliente,canal_captacion,antiguedad_cliente_meses,fecha_registro,sucursal_id,estado_cliente,dwh_fecha_carga
0,1,DNI,60366909,Carmen,Ramírez,Flores,1977-09-16,48,Femenino,Casado,...,888.76,39631.77,550,Regular,Agencia,122,2016-05-07,14,Activo,2026-08-03 18:46:04.580
1,2,DNI,62729806,Cecilia,Cusi,Cusi,1964-03-13,62,Femenino,Casado,...,3037.05,125691.99,528,Regular,Digital,105,2017-10-18,13,Activo,2026-08-03 18:46:04.580
2,3,CE,641708053,Juan,Ortiz,Medina,1964-08-01,62,Masculino,Casado,...,2302.13,226055.14,493,Regular,Agencia,90,2019-01-08,13,Activo,2026-08-03 18:46:04.580
3,4,DNI,29912419,Carlos,Flores,Morales,1976-11-09,49,Masculino,Soltero,...,763.53,104986.09,490,Regular,Telemarketing,196,2010-03-12,15,Activo,2026-08-03 18:46:04.580
4,5,DNI,86518506,Sandra,González,Morales,1980-11-20,45,Femenino,Viudo,...,405.03,37044.25,392,Regular,Digital,162,2013-01-08,4,Activo,2026-08-03 18:46:04.580

In [8]:
# Verifica si existen registro duplicados 
# Resultados Esperados: Tabla Vacia
df_clientes_tra[df_clientes_tra.duplicated(keep=False)].sort_values(by='cliente_id')

Empty DataFrame
Columns: [cliente_id, tipo_documento, numero_documento, nombres, apellido_paterno, apellido_materno, fecha_nacimiento, edad, genero, estado_civil, nivel_educacion, ocupacion, sector_economico, ciudad_residencia, departamento_residencia, region_residencia, ingresos_mensuales, egresos_mensuales, patrimonio_estimado, score_crediticio, segmento_cliente, canal_captacion, antiguedad_cliente_meses, fecha_registro, sucursal_id, estado_cliente, dwh_fecha_carga]
Index: []

[0 rows x 27 columns]

## cliente_id

In [9]:
# Verifica si existen ids negativos o 0 
# Resultados Esperados: Tabla Vacia
df_clientes_tra[df_clientes_tra.cliente_id <= 0]

Empty DataFrame
Columns: [cliente_id, tipo_documento, numero_documento, nombres, apellido_paterno, apellido_materno, fecha_nacimiento, edad, genero, estado_civil, nivel_educacion, ocupacion, sector_economico, ciudad_residencia, departamento_residencia, region_residencia, ingresos_mensuales, egresos_mensuales, patrimonio_estimado, score_crediticio, segmento_cliente, canal_captacion, antiguedad_cliente_meses, fecha_registro, sucursal_id, estado_cliente, dwh_fecha_carga]
Index: []

[0 rows x 27 columns]

In [10]:
# Resultados Esperados: Tabla Vacia 
df_clientes_tra[df_clientes_tra.cliente_id.duplicated(keep=False)]

Empty DataFrame
Columns: [cliente_id, tipo_documento, numero_documento, nombres, apellido_paterno, apellido_materno, fecha_nacimiento, edad, genero, estado_civil, nivel_educacion, ocupacion, sector_economico, ciudad_residencia, departamento_residencia, region_residencia, ingresos_mensuales, egresos_mensuales, patrimonio_estimado, score_crediticio, segmento_cliente, canal_captacion, antiguedad_cliente_meses, fecha_registro, sucursal_id, estado_cliente, dwh_fecha_carga]
Index: []

[0 rows x 27 columns]

## tipo_documento

In [11]:
# Resultados Esperados: 'DNI', 'CE', 'Pasaporte'
df_clientes_tra.tipo_documento.unique()

array(['DNI', 'CE', 'Pasaporte'], dtype=object)

## numero_documento

In [12]:
# Verifica si la cantidad de digitos son correctos para cada tipo de documento 
# Resultados Esperados: Tabla Vacia
df_clientes_tra[   
    (    # DNIs que no tengan 8 digitos
            (
            (df_clientes_tra.tipo_documento == 'DNI') 
            & (df_clientes_tra.numero_documento.str.len() != 8)
            )
            # CE que no tengan 9 digitos
        |   (
            (df_clientes_tra.tipo_documento == 'CE') 
            & (df_clientes_tra.numero_documento.str.len() != 9)
            )
            # Pasaporte que tenga menos de 6 digitos y mas de 12 
        |   (
            (df_clientes_tra.tipo_documento == "Pasaporte") &
            (
                (df_clientes_tra.numero_documento.str.len() < 6) 
                |   (df_clientes_tra.numero_documento.str.len() > 12)
            )
            )
    )
    & 
    (
        df_clientes_tra.numero_documento != "n/a"
    )
]

Empty DataFrame
Columns: [cliente_id, tipo_documento, numero_documento, nombres, apellido_paterno, apellido_materno, fecha_nacimiento, edad, genero, estado_civil, nivel_educacion, ocupacion, sector_economico, ciudad_residencia, departamento_residencia, region_residencia, ingresos_mensuales, egresos_mensuales, patrimonio_estimado, score_crediticio, segmento_cliente, canal_captacion, antiguedad_cliente_meses, fecha_registro, sucursal_id, estado_cliente, dwh_fecha_carga]
Index: []

[0 rows x 27 columns]

## nombres

In [13]:
# Nombres que tienen formatos incorrectos 
# Resultados Esperados Tabla Vacia
df_clientes_tra.nombres[df_clientes_tra.nombres != df_clientes_tra.nombres.str.strip().str.title()]

Series([], Name: nombres, dtype: object)

## apellido_paterno

In [14]:
# Apellidos que tienen formatos incorrectos
# Resultados Esperados Tabla Vacia
df_clientes_tra.apellido_paterno[df_clientes_tra.apellido_paterno 
                                != df_clientes_tra.apellido_paterno.str.strip().str.capitalize()]

Series([], Name: apellido_paterno, dtype: object)

## apellido_materno

In [15]:
# Apellidos que tienen formatos incorrectos
# Resultados Esperados Tabla Vacia
df_clientes_tra.apellido_materno[df_clientes_tra.apellido_materno 
                                != df_clientes_tra.apellido_materno.str.strip().str.capitalize()]

Series([], Name: apellido_materno, dtype: object)

## fecha_nacimiento

In [16]:
# Verifica si existen fechas con errores 
fechas_error_nacimiento = pd.to_datetime(
    df_clientes_tra.fecha_nacimiento, 
    errors='coerce'
)
# Muestras las fechas que generan error 
# Resultados Esperados: Tabla Vacia 
df_clientes_tra.fecha_nacimiento[fechas_error_nacimiento.isna()]

Series([], Name: fecha_nacimiento, dtype: datetime64[ns])

In [17]:
# Verifica si existen fechas de nacimiento futuras o fechas muy antiguas 
# Resultados Esperados: 12 registros con fechas anterirores a 1950 
df_clientes_tra.fecha_nacimiento[
    (df_clientes_tra.fecha_nacimiento.dt.date >= date.today())
    | (df_clientes_tra.fecha_nacimiento <= pd.to_datetime('1950-01-01',format='%Y-%m-%d'))
]

965    1949-07-21
1719   1949-02-20
1891   1949-04-23
1932   1949-05-07
2246   1949-05-10
2297   1949-05-03
2624   1949-09-26
3086   1949-07-09
3395   1949-03-30
3527   1949-06-29
4236   1949-03-07
4402   1949-12-27
Name: fecha_nacimiento, dtype: datetime64[ns]

## edad

In [18]:
# Resultados Esperados: Los resultados pueden variar segun el momento de ejecucion del codigo, tanto el de limpieza como el de verificacion. 
# POR ESO NO SE TIENEN QUE GUARDAR COLUMNAS DERIVADAS DE OTRAS, como edad que depende de FECHA_NACIMIENTO
fecha_actual = date.today()
recalculo_edad = (
    fecha_actual.year
    - df_clientes_tra.fecha_nacimiento.dt.year
    - (
        (fecha_actual.month < df_clientes_tra.fecha_nacimiento.dt.month)
        |
        (
            (fecha_actual.month == df_clientes_tra.fecha_nacimiento.dt.month)
            &
            (fecha_actual.day < df_clientes_tra.fecha_nacimiento.dt.day)
        )
    )
)
df_clientes_tra[df_clientes_tra.edad != recalculo_edad]

Empty DataFrame
Columns: [cliente_id, tipo_documento, numero_documento, nombres, apellido_paterno, apellido_materno, fecha_nacimiento, edad, genero, estado_civil, nivel_educacion, ocupacion, sector_economico, ciudad_residencia, departamento_residencia, region_residencia, ingresos_mensuales, egresos_mensuales, patrimonio_estimado, score_crediticio, segmento_cliente, canal_captacion, antiguedad_cliente_meses, fecha_registro, sucursal_id, estado_cliente, dwh_fecha_carga]
Index: []

[0 rows x 27 columns]

## genero

In [19]:
# Muestra los valores unicos de genero
# Resultados Esperados: "FEMENINO", "MASCULINO", "n/a"
df_clientes_tra.genero.unique()

array(['Femenino', 'Masculino'], dtype=object)

## estado_civil

In [20]:
# Resultados Esperados: 'Casado', 'Soltero', 'Viudo', 'Divorciado', 'Conviviente', 'n/a'
df_clientes_tra.estado_civil.unique()

array(['Casado', 'Soltero', 'Viudo', 'Divorciado', 'Conviviente'],
      dtype=object)

## nivel_educacion

In [21]:
# Resultados Esperados: 'Secundaria', 'Universitario', 'Técnico', 'Postgrado', 'n/a'
df_clientes_tra.nivel_educacion.unique()

array(['Secundaria', 'Universitario', 'Técnico', 'Postgrado', 'n/a'],
      dtype=object)

## ocupacion

In [22]:
# Resultados esperados: 'Empleado Público', 'Empresario', 'Empleado Privado', 'Independiente', 'Pensionista',    'Estudiante', 'n/a'
df_clientes_tra.ocupacion.unique()

array(['Empleado Público', 'Empresario', 'Empleado Privado',
       'Independiente', 'Pensionista', 'Estudiante', 'n/a'], dtype=object)

## sector_economico

In [23]:
# Resultados Esperados: 'Transporte', 'Servicios', 'Otro', 'Comercio', 'Manufactura', 'Tecnología', 'Salud', 'Finanzas','Educación', 'Construcción', 'Agricultura'
df_clientes_tra.sector_economico.unique()

array(['Transporte', 'Servicios', 'Otro', 'Comercio', 'Manufactura',
       'Tecnología', 'Salud', 'Finanzas', 'Educación', 'Construcción',
       'Agricultura'], dtype=object)

## ciudad_residencia

In [24]:
# Verifica el formato de ciudad_residencia
# Resultados Esperados: Santiago de Surco, San Juan de Lurigancho
df_clientes_tra.ciudad_residencia[df_clientes_tra.ciudad_residencia 
                                != df_clientes_tra.ciudad_residencia.str.strip().str.title()].unique()

array(['Santiago de Surco', 'San Juan de Lurigancho'], dtype=object)

In [25]:
# Valida si todas las ciudades de residencia de clientes, se encuentra en el registro de la empresa 
# Resultados Esperados: both: 5000, left_only: 0, right_only: 0
verificar_ciudad = df_clientes_tra.merge(
    right=df_ciudades_tra,
    right_on='ciudad',
    left_on='ciudad_residencia',
    indicator=True)

verificar_ciudad._merge.value_counts()

_merge
both          5000
left_only        0
right_only       0
Name: count, dtype: int64

## departamento_residencia

In [26]:
# Verifica el formato de departamento_residencia
# Resultados Esperados: Tabla Vacia
df_clientes_tra.departamento_residencia[df_clientes_tra.departamento_residencia 
                                != df_clientes_tra.departamento_residencia.str.strip().str.title()]

Series([], Name: departamento_residencia, dtype: object)

In [27]:
# Valida si todas los departamentos de residencia de los clientes, se encuentran en el registro de la empresa 
# Resultados Esperados: Tabla Vacia 
verificar_departamento = df_clientes_tra.merge(
    right=df_ciudades_tra,
    right_on='ciudad',
    left_on='ciudad_residencia'
    )

verificar_departamento[verificar_departamento.departamento_residencia != verificar_departamento.departamento]

Empty DataFrame
Columns: [cliente_id, tipo_documento, numero_documento, nombres, apellido_paterno, apellido_materno, fecha_nacimiento, edad, genero, estado_civil, nivel_educacion, ocupacion, sector_economico, ciudad_residencia, departamento_residencia, region_residencia, ingresos_mensuales, egresos_mensuales, patrimonio_estimado, score_crediticio, segmento_cliente, canal_captacion, antiguedad_cliente_meses, fecha_registro, sucursal_id, estado_cliente, dwh_fecha_carga, ciudad, departamento, region]
Index: []

[0 rows x 30 columns]

## region_residencia

In [28]:
# Verifica el formato de ciudad_residencia
# Resultados esperados: Lima y Callao
df_clientes_tra.region_residencia[df_clientes_tra.region_residencia 
                                != df_clientes_tra.region_residencia.str.strip().str.title()].unique()

array(['Lima y Callao'], dtype=object)

In [29]:
# Valida si todas las regiones de residencia de los clientes, se encuentran en el registro de la empresa 
# Resultados Esperados: Tabla Vacia 
verificar_region = df_clientes_tra.merge(
    right=df_ciudades_tra,
    right_on='ciudad',
    left_on='ciudad_residencia'
    )

verificar_region[verificar_region.region_residencia != verificar_region.region]

Empty DataFrame
Columns: [cliente_id, tipo_documento, numero_documento, nombres, apellido_paterno, apellido_materno, fecha_nacimiento, edad, genero, estado_civil, nivel_educacion, ocupacion, sector_economico, ciudad_residencia, departamento_residencia, region_residencia, ingresos_mensuales, egresos_mensuales, patrimonio_estimado, score_crediticio, segmento_cliente, canal_captacion, antiguedad_cliente_meses, fecha_registro, sucursal_id, estado_cliente, dwh_fecha_carga, ciudad, departamento, region]
Index: []

[0 rows x 30 columns]

## ingresos_mensuales

In [30]:
# Verifica si existen ingresos_mensuales mmenores o iguales a 0
# Resultados esperados: Tabla Vacia 
df_clientes_tra.ingresos_mensuales[df_clientes_tra.ingresos_mensuales <= 0]

Series([], Name: ingresos_mensuales, dtype: float64)

## egresos_mensuales

In [31]:
# Verifica si existen egresos_mensuales mmenores o iguales a 0
# Resultados esperados: Tabla Vacia
df_clientes_tra.egresos_mensuales[df_clientes_tra.egresos_mensuales <= 0 ]

Series([], Name: egresos_mensuales, dtype: float64)

## patrimonio_estimado

In [32]:
# Verifica si existen valores en patrimonio_estimado menores o iguales a 0 
# Resultados Esperados: Tabla Vacia 
df_clientes_tra.patrimonio_estimado[df_clientes_tra.patrimonio_estimado <= 0]

Series([], Name: patrimonio_estimado, dtype: float64)

## score_crediticio

In [33]:
# Verifica si existen valores en score_crediticio que sean menores a 0 o que sean mayores a 1000 
# Resultados Esperados: Tabla Vacia 
df_clientes_tra.score_crediticio[(df_clientes_tra.score_crediticio < 0) | (df_clientes_tra.score_crediticio > 1000)]

Series([], Name: score_crediticio, dtype: int64)

## segmento_cliente

In [34]:
# Muestra los valores unicos
# Resultados esperados: 'Regular', 'Premium', 'Vip'
df_clientes_tra.segmento_cliente.unique()

array(['Regular', 'Premium', 'VIP'], dtype=object)

## canal_captacion

In [35]:
# Muestra los valores unicos
# Resultados Esperados:'Agencia', 'Digital', 'Telemarketing', 'Referido', 'Campaña Institucional', 'n/a'
df_clientes_tra.canal_captacion.unique()

array(['Agencia', 'Digital', 'Telemarketing', 'Referido',
       'Campaña Institucional', 'n/a'], dtype=object)

## fecha_registro

In [36]:
# Verifica si existen fechas con formatos incorrectos
# Resultados Esperados: Tabla Vacia 
fechas_error_registro = pd.to_datetime(df_clientes_tra.fecha_registro, errors='coerce')
df_clientes_tra.fecha_registro[(fechas_error_registro.isna())]

Series([], Name: fecha_registro, dtype: datetime64[ns])

In [37]:
# Verifica si existen fechas de registro futuras 
# Resultados Esperados: Tabla Vacia 
df_clientes_tra[['cliente_id','fecha_nacimiento','edad','fecha_registro','antiguedad_cliente_meses']][
    df_clientes_tra.fecha_registro.dt.date >= date.today()
]

Empty DataFrame
Columns: [cliente_id, fecha_nacimiento, edad, fecha_registro, antiguedad_cliente_meses]
Index: []

In [38]:
# Verifica si existen registros donde la fecha_nacimiento sea mayor o igual a la fecha_registro
# Resultados Esperados: Tabla Vacia 
df_clientes_tra.fecha_registro[df_clientes_tra.fecha_nacimiento >= df_clientes_tra.fecha_registro]

Series([], Name: fecha_registro, dtype: datetime64[ns])

In [ ]:
# Verifica que la fecha de registro sea cuando el cliente tiene 18 años o mas 
prueba_fechas = df_clientes_tra.copy()
prueba_fechas["edad_registro"] = (
    prueba_fechas.fecha_registro.dt.year
    - prueba_fechas.fecha_nacimiento.dt.year
    - ( 
        (prueba_fechas.fecha_registro.dt.month < prueba_fechas.fecha_nacimiento.dt.month)
        |
        (
            (prueba_fechas.fecha_registro.dt.month == prueba_fechas.fecha_nacimiento.dt.month)
            &
            (prueba_fechas.fecha_registro.dt.day < prueba_fechas.fecha_nacimiento.dt.day)
        )
    )
)

# Selecciona los registros con fechas erroneas 
# Resultados Esperados: Tabla Vacia
prueba_fechas[prueba_fechas.edad_registro <18]

Empty DataFrame
Columns: [cliente_id, tipo_documento, numero_documento, nombres, apellido_paterno, apellido_materno, fecha_nacimiento, edad, genero, estado_civil, nivel_educacion, ocupacion, sector_economico, ciudad_residencia, departamento_residencia, region_residencia, ingresos_mensuales, egresos_mensuales, patrimonio_estimado, score_crediticio, segmento_cliente, canal_captacion, antiguedad_cliente_meses, fecha_registro, sucursal_id, estado_cliente, dwh_fecha_carga, edad_registro]
Index: []

[0 rows x 28 columns]

## antiguedad_cliente_meses

In [40]:
# Resultados Esperados: Los resultados pueden variar segun el momento de ejecucion del codigo, tanto el de limpieza como el de verificacion. 
# POR ESO NO SE TIENEN QUE GUARDAR COLUMNAS DERIVADAS DE OTRAS, como antiguedad_cliente_meses que depende de FECHA_REGISTRO
fecha_actual = date.today()

verificar_antiguedad_cliente_meses = (
    (fecha_actual.year - df_clientes_tra.fecha_registro.dt.year) * 12
    + (fecha_actual.month - df_clientes_tra.fecha_registro.dt.month)
    - ( fecha_actual.day < df_clientes_tra.fecha_registro.dt.day)
)


df_clientes_tra[df_clientes_tra.antiguedad_cliente_meses != verificar_antiguedad_cliente_meses]

Empty DataFrame
Columns: [cliente_id, tipo_documento, numero_documento, nombres, apellido_paterno, apellido_materno, fecha_nacimiento, edad, genero, estado_civil, nivel_educacion, ocupacion, sector_economico, ciudad_residencia, departamento_residencia, region_residencia, ingresos_mensuales, egresos_mensuales, patrimonio_estimado, score_crediticio, segmento_cliente, canal_captacion, antiguedad_cliente_meses, fecha_registro, sucursal_id, estado_cliente, dwh_fecha_carga]
Index: []

[0 rows x 27 columns]

## sucursal_id

In [41]:
# Resultados Esperados: Tabla Vacia
df_clientes_tra.sucursal_id[df_clientes_tra.sucursal_id <= 0]

Series([], Name: sucursal_id, dtype: int64)

In [42]:
# Verificamos que todas las sucursales estén dentro de la tabla de sucursales 
# Resultados Esperados: both: 5000, left_only: 0, right_only: 0
df_clientes_veri = df_clientes_tra[['cliente_id','sucursal_id','fecha_registro']].copy()
df_sucursales_veri = df_sucursales_tra.copy()
df_merge_veri_sucursal = df_clientes_veri.merge(
    right=df_sucursales_veri,
    on="sucursal_id",
    how='left',
    indicator=True)
df_merge_veri_sucursal._merge.value_counts()

_merge
both          5000
left_only        0
right_only       0
Name: count, dtype: int64

In [43]:
# Verifica si existen registros donde la fecha de registro del cliente es menor a la fecha de apertura de la sucursal asociada
# Resultados Esperados: Tabla Vacia
df_merge_veri_sucursal[df_merge_veri_sucursal.fecha_registro < df_merge_veri_sucursal.fecha_apertura]

Empty DataFrame
Columns: [cliente_id, sucursal_id, fecha_registro, fecha_apertura, _merge]
Index: []

## estado_cliente

In [ ]:
# Resultados Esperados: 'Activo', 'Inactivo', 'Bloqueado'
# No requiere cambios
df_clientes_tra.estado_cliente.unique()

array(['Activo', 'Inactivo', 'Bloqueado'], dtype=object)